project: mjlab
program: vbrl.scripts.train
name: lift_cube_rgb_real_texture_dinov2_vits14_spatial_softmax
method: bayes
run_cap: 6
metric: {name: Metrics/lift_height/episode_success, goal: maximize}
command:
  - ${env}
  - python
  - -m
  - ${program}
  - Mjlab-LiftCube-RealTexture-DinoV2ViTS14-SpatialSoftmax-Trossen
  - --env.scene.num-envs
  - "1024"
  - --gpu-ids
  - all
  - ${args_no_boolean_flags}

parameters:
  agent.algorithm.learning-rate: {distribution: log_uniform_values, min: 0.00010, max: 0.00030}
  agent.algorithm.num-learning-epochs: {values: [3, 5]}
  agent.algorithm.num-mini-batches: {values: [16, 32]}
  agent.algorithm.desired-kl: {values: [0.025, 0.030, 0.035]}
  agent.algorithm.entropy-coef: {values: [0.002, 0.003, 0.005]}
